version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  etl:
    build: .
    stdin_open: true
    tty: true
    environment:
      - AWS_PROFILE=default
    volumes:
      - .:/macpaw-de
      - ~/.aws/:/root/.aws:ro
volumes:
  database-data: # named volumes can be managed easier using docker-compose